### ISSUE TITLE
Make offer page: click on others. provide two field, one is "what is the contact method", another is "what is the contact info"

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#11]

**Comment by b25paWNoYW4** [comment]
Need more information
@lisirrx @gy2003 @FachengG 
What do you think if we add the priority level into the title when the issue was created?

**Comment by FachengG** [comment]
@b25paWNoYW4 
in the 'Contact information', when select 'other', two new field need to pop up.
One is "what is the contact method", another is "what is the contact info"
