### ISSUE TITLE
[BUG]Google auth

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#35]
Google auth is stuck in loop. This happened on a Chrome browser on mobile. This bug did not occur on a Safari browser.

**Expected Behavior:** After authorizing through Google, user should be directed back to LDM.
![image](https://github.com/LocalDealMarket/feedback/assets/16894756/edffea78-a2ed-410f-a4d9-c80b99f7b837)

**Comment by b25paWNoYW4** [comment]
can not reproduce
