### ISSUE TITLE
[BUG]Map interaction in adding new location

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#38]
The pin on the map cannot be dragged or moved to another location.

**Expected Behavior:** The user should be able to move the pin to another location when the user wants to adjust the location.
![image](https://github.com/LocalDealMarket/feedback/assets/16894756/7807ecb9-2e0f-4346-873b-fc06ff2ea2db)

**Comment by gy2003** [comment]
**Expected Behavior:** The map should be zoomed out. The map should be fixed, not interactive. Replace the message at the bottom: "Please ensure that the circle covers your item location". 

https://docs.google.com/spreadsheets/d/1otPPZ5Y2s7ugWsCbUUJ2JhxpPFjfjTQWulbkxN7n34w/edit?gid=0#gid=0
DEF-010
