### ISSUE TITLE
[BUG]Sign up

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#40]
When I use email to sign up, I'm returned to the login page though I have received the OTP code from LDM. This happened on both Chromo and Safari browsers on mobile.

**Expected Behavior:** When users sign up via email, they should be directed to email verification page.
![image](https://github.com/LocalDealMarket/feedback/assets/16894756/53315197-2433-4da7-95b9-72087680bcf9)

**Comment by gy2003** [comment]
This bug has been merged.

**Comment by FachengG** [comment]
@gy2003 is it fixed?

**Comment by gy2003** [comment]
@FachengG Yes
