### ISSUE TITLE
[BUG]My Favorites page

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#43]
The saved to favorites items did not sync up between the My Favorites page and the homepage. This happened when I unsaved the item in the My Favorites page, the item on the homepage still shows being saved. This happened on both Chrome and Safari browsers on mobile.

**Expected Behavior:** The saved items should be the same between the homepage and My Favorites page.
![image](https://github.com/LocalDealMarket/feedback/assets/16894756/fa438641-c3f7-4af1-b776-8209e5579be5)
![image](https://github.com/LocalDealMarket/feedback/assets/16894756/05f10c17-bbb6-4099-96d6-352f1aa70597)

**Comment by tangyunpei** [comment]
cannot repeat the bug in latest version, please recheck @lisirrx
