### ISSUE TITLE
[BUG]Item listing time

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#44]
After I finished the listing of an item, it took more than 10 min for the item to show up on the homepage.

**Expected Behavior:** After users complete the listing of an item, the listing should show up on the homepage immediately.

**Comment by b25paWNoYW4** [comment]
Need more detail information

**Comment by FachengG** [comment]
After successfully upload the item. The FE also should save the uploaded info as [data]. 
When the user went to back to homepage, the new item should be there.

Current logic:
when go back to the home page, it is not refreshed, so the new item cannot be return from server.
Refresh the page also does not guarantee the user will see its item (if user publish the item at a location far away)

@b25paWNoYW4

**Comment by b25paWNoYW4** [comment]
不在前端处理
