### ISSUE TITLE
[BUG]Location book entry

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#49]
When I enter zipcode, I can see locations outside of US. 
**Expected Behavior:**
We should limit to US-only locations.

**Comment by b25paWNoYW4** [comment]
@gy2003 
Contact me if you need anything

**Comment by lisirrx** [comment]
@b25paWNoYW4 @gy2003 any update?

**Comment by b25paWNoYW4** [comment]
@gy2003 @lisirrx 这个已经修复了吧
