### ISSUE TITLE
[DEF-027][Ordering]After seller accepts an offer, items are still on the homepage and other offfers can still be made to this same item. 

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#55]
We can mark items as sold on the platform, but no additional offers can be made to the items that have offers accepted. Only show items that are sold on the same day/recent days Show limited number of sold items.

**Comment by b25paWNoYW4** [comment]
fixed
https://github.com/LocalDealMarket/LocalDealMarket_BE/pull/102
