### ISSUE TITLE
[DEF-029][Review offers]Sellers can still decline offer after the another offer was already accepted on the same item.

### ISSUE THREAD

**Issue by lisirrx** [LocalDealMarket/feedback#57]
All remaining offers should be auto declined by the system if an offer is already accepted on the item. This should come together with DEF-027, i.e. no offers can be made to items that are sold.

**Comment by b25paWNoYW4** [comment]
fixed
https://github.com/LocalDealMarket/LocalDealMarket_BE/pull/102
