### ISSUE TITLE
DEF-035 Review offers

### ISSUE THREAD

**Issue by FachengG** [LocalDealMarket/feedback#71]
Problem:
When reviewing offer details, buyer pickup is by default.

Expectation:
"buyer pickup" should be removed from the offer details for now. In future, we need to provide options to both buyer and selller to select shipping methods.

![Image](https://github.com/user-attachments/assets/95260527-0425-4eb6-b601-f8c6769cac1c)

**Comment by b25paWNoYW4** [comment]
@FachengG email 里面的shipping method是不是也要remove掉

**Comment by FachengG** [comment]
> @FachengG email 里面的shipping method是不是也要remove掉

嗯。confirmation里要保留的，其他邮件去掉

**Comment by FachengG** [comment]
apple privacy email may block email.
We must require user to provide a valid email after register with apple.
