### ISSUE TITLE
DEF-044: Listing picture upload bug

### ISSUE THREAD

**Issue by FachengG** [LocalDealMarket/feedback#80]
Problem:
After user uploaded one photo, users didn't see a sign/prompt to add additional photos.

Expectation:
1. The "camera" sign should be changed to either "+"(solid black, not grey. grey feel unuseable.) or "upload additional photos".

2. allow user to change picture to be re-order by user. 
This is important that user may want to change its cover picture (default the first picture is the cover picture)

![Image](https://github.com/user-attachments/assets/f5d42ed4-b7eb-4ecc-8317-bf061ac34416)

**Comment by gy2003** [comment]
<img width="365" alt="截屏2024-07-20 01 23 12" src="https://github.com/user-attachments/assets/10969281-51c9-4859-83d9-f19ed5f0dd3a">
The new UI will be used.
